version: "3.9"

services:
  server:
    build: .
    container_name: cluster-server
    command: ["python", "app.py", "--role", "server", "--server-port", "5000"]
    ports:
      - "5000:5000"
    volumes:
      - ./shared:/home/parth/projects/p2pCluster
    networks:
      - cluster

  client:
    build: .
    # Name will be auto-suffixed when scaled (client-1, client-2...)
    command: ["python", "app.py", "--role", "client", "--server-host", "server", "--server-port", "5000"]
    depends_on:
      - server
    volumes:
      - ./shared:/home/parth/projects/p2pCluster
    networks:
      - cluster

networks:
  cluster:
    driver: bridge
