version: "3.9"

services:
  server:
    build: .
    command: ["--role", "server", "--server-port", "5000"]
    ports:
      - "8000:5000"
    volumes:
      - ./shared:/app/shared
    networks:
      - cluster

  client:
    build: .
    command: ["--role", "client", "--server-host", "server", "--server-port", "5000"]
    depends_on:
      - server
    volumes:
      - ./shared:/app/shared
    networks:
      - cluster

networks:
  cluster:
    driver: bridge
